### PR TITLE
feat(entities-plugins): add default values in protocols placeholder

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
# Summary

In plugin forms:
1. Adding default values to the placeholder of the protocols field in GM
2. Removing all default values from placeholders in KM

| GM | KM |
| - | - |
| image | image |

KM-526

### CODE REVIEW

**Review by Justineo — APPROVED** [review]
LGTM

I think we should create a ticket to track the different behavior between KM/GM.

**Comment by Leopoldthecoder** [comment]
> LGTM
> 
> I think we should create a ticket to track the different behavior between KM/GM.

Do you think we need a `KM` ticket in addition to https://konghq.atlassian.net/browse/KAG-5576?

**Comment by Justineo** [comment]
Maybe create one for frontend changes on our side and link it to KAG-5576?

**Comment by Leopoldthecoder** [comment]
Created https://konghq.atlassian.net/browse/KM-600

**Pull request merged**
