### PR TITLE
style: update styling and color for document viewer (TDX-2774)

### PR DESCRIPTION
**Pull request by davidma415**
# Summary
Update some styling of the `DocumentViewer` to match the designs more.

## PR Checklist

* [ ] **Naming & Structure:** the files and package structure use the conventions outlined in the [Creating a Package docs](https://github.com/Kong/public-ui-components/blob/main/docs/creating-a-package.md).
* [ ] **Tests pass:** check the output of all package unit and/or component tests.
  * [ ] If this PR is the result of a bug, test coverage was added accordingly.
* [ ] **Functional:** all changes do not break existing APIs, but if so, a BREAKING CHANGE commit is in place to bump the major version.
* [ ] **Conventional Commits** all commits follow the conventional commit standards [outlined in the main README](https://github.com/Kong/public-ui-components#committing-changes).
* [ ] **Docs:** includes a technically accurate README, and the docs have been updated accordingly based on the changes in this PR.

### CODE REVIEW

**Comment by davidma415** [comment]
@tkajtoch I have ported over the styles here. I left the tables / images portion as they are for now, let me know if we should adjust them or if that should come in the future.

**Comment by Leopoldthecoder** [comment]
Hi @davidma415, please pull the latest `main` branch to resolve the CI failure.

**Comment by tkajtoch** [comment]
LGTM. I'll rename CSS Variables to match the guidelines and fix Node components' prop names in another PR

**Review by tkajtoch — APPROVED** [review]

**Review by adamdehaven — APPROVED** [review]
LGTM

**Pull request merged**
