### PR TITLE
feat(entities-plugins): enable more plugins to consumer groups

### PR DESCRIPTION
**Pull request by sumimakito**
# Summary

This pull request enables more plugins to consumer groups:

1. rate-limiting
2. ip-restriction 
3. request-termination
4. proxy-cache
5. proxy-cache advanced

KAG-3449

### CODE REVIEW

**Comment by sumimakito** [comment]
Manually tested in the sandbox with Gateway Admin API and Konnect API (all dev) and everything looked fine.

**Review by Leopoldthecoder — APPROVED** [review]
LGTM

**Review by raoxiaoyan — APPROVED** [review]

**Comment by Leopoldthecoder** [comment]
📣Hold off merging until backend changes are effective.

**Comment by sumimakito** [comment]
Received updates from @GGabriele that these changes are available in Konnect prod env, marking this PR as ready to be reviewed and merged.

**Pull request merged**
